name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: dev_publish
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish
          docker-compose -f tasks/ci/docker-compose.yml run publish
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: dev_deploy
        env:
          Environment: dev
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: integration
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build integration
          docker-compose -f tasks/ci/docker-compose.yml run integration
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: prod_publish
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish
          docker-compose -f tasks/ci/docker-compose.yml run publish
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: prod_deploy
        env:
          Environment: prod
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
